import { SiteContent } from './types';

export const en: SiteContent = {
  metadata: {
    title: 'Legal Support in Ukraine for Clients Abroad | Olga Sanamyan',
    description: 'Ukrainian lawyers for clients abroad: inheritance, property, family, criminal and military matters, with representation throughout Ukraine.',
  },
  header: {
    name: 'Olga Sanamyan',
    nav: [
      { name: 'How It Works', href: '#how-it-works' },
      { name: 'Services', href: '#services' },
      { name: 'FAQ', href: '#faq' },
      { name: 'Contact', href: '#contact' },
    ],
  },
  hero: {
    badge: 'Legal Representation in Ukraine',
    title: 'Legal Support in Ukraine for Clients Abroad',
    subtitle: 'Ukrainian lawyers assisting clients in the United States, Canada, Europe and other countries with legal matters throughout Ukraine.',
    highlight: 'In many cases, you do not need to travel to Ukraine.',
    description: '20+ years of practice. 5,000+ clients.',
    ctaPrimary: 'Request a Consultation',
    ctaSecondary: 'Message Us',
    ctaSecondaryHref: '#messengers',
    phone: '+38(098)720-83-01',
    phone2: '+38(050)929-53-74',
    formTitle: 'Request a Consultation',
    formSubtitle: 'Tell us what happened. Briefly describe your situation and we will explain what information or documents we need next.',
    formName: 'Your name',
    formPhone: 'Phone number',
    formMessage: 'Describe your situation',
    formSubmit: 'Send',
    formSending: 'Sending...',
    formSuccess: 'Thank you! We have received your request and will get back to you.',
    formError: 'Something went wrong. Please try again or contact us via messenger.',
    alertInvalidPhone: 'Please enter a valid phone number (digits, +, -, () only)',
    alertXss: 'Forbidden characters detected',
    alertCopied: 'Number copied!',
    alertCopyFailed: 'Failed to copy',
    alertRateLimited: 'Too many requests. Please try again later.',
    titlePhoneHint: 'Digits, +, -, () only',
    btnTryAgain: 'Try Again',
    btnCancel: 'Cancel',
    imageAlt: 'Attorney',
  },
  stats: [
    { number: '20+', label: 'years of experience' },
    { number: '5,000+', label: 'clients assisted' },
    { number: 'Throughout Ukraine', label: 'nationwide legal representation', compact: true },
    { image: '/icons/confidentiality.png', label: 'confidential handling' },
  ],
  howItWorks: {
    title: 'How It Works Remotely',
    subtitle: 'Many legal matters in Ukraine can be handled while you remain abroad.',
    steps: [
      { title: 'Tell us about your situation', desc: 'Describe your problem and send the documents you have.' },
      { title: 'We assess the matter', desc: 'We analyze your situation, the possible courses of action and the scope of work.' },
      { title: 'We arrange representation', desc: 'If needed, we explain what documents or authorizations must be arranged from abroad.' },
      { title: 'We act in Ukraine', desc: 'We take the agreed legal steps in Ukraine and keep you updated remotely.' },
    ],
  },
  services: {
    title: 'Legal Services',
    subtitle: 'Practice areas for clients outside Ukraine',
    items: [
      { icon: '/icons/inheritance.png', title: 'Inheritance & Estate Matters', items: ['Consultations on inheritance procedures in Ukraine', 'Assistance with inheritance proceedings in Ukraine', 'Recognition of inheritance rights through court', 'Establishing legally significant facts (family ties, residence, etc.)', "Challenging a will or a notary's actions", 'Division of inherited property among heirs', 'Seeking an additional period to accept an inheritance', 'Court representation'] },
      { icon: '/icons/location.png', title: 'Property & Real Estate Matters', items: ['Legal support for real estate transactions', 'Verification of property, documents and sellers', 'Real estate disputes and litigation', 'Property rights of owners residing abroad', 'Representation before registries and authorities'] },
      { icon: '/icons/family.png', title: 'Family Law & Divorce', items: ['Divorce, including cases where a spouse resides abroad', 'Division of marital property', 'Child support and related arrears', "Determining the child's place of residence", 'Termination of parental rights', 'Adoption'] },
      { icon: '/icons/civil.png', title: 'Civil Litigation & Disputes', items: ['Establishing legally significant facts', 'Debt collection under loan agreements', 'Invalidation of contracts', 'Compensation for property damage', 'Representation in Ukrainian courts at all levels'] },
      { icon: '/icons/criminal.png', title: 'Criminal Defense & Representation', items: ['Defense of suspects and accused persons at all stages of criminal proceedings', "Representation of victims' interests", 'Assistance during interrogations, searches and detentions', 'Appeals and challenges concerning preventive measures and procedural decisions', 'Preparation of procedural documents', 'Defense in courts of first instance and appeal'] },
      { icon: '/icons/military.png', title: 'Military & Mobilization Matters', items: ['Consultations on military registration and mobilization', 'Appeals against decisions of Territorial Recruitment and Social Support Centers (TCCs) and military medical commissions (MMC)', 'Support during MMC examinations', 'Protection of the rights of service members and conscripts', 'Assistance with deferment and discharge from service', 'Legal assistance in cases involving unauthorized absence from military service', 'Preparation of complaints, reports and applications'] },
      { icon: '/icons/dtp.png', title: 'Road Traffic Accident Cases', items: ['Consultations on road accidents and their legal consequences', 'Defense in administrative offence cases', 'Representation in criminal proceedings related to accidents', 'Challenging police materials and court decisions', 'Compensation for property and non-pecuniary damages', 'Disputes with insurance companies'] },
      { icon: '/icons/target.png', title: 'Complex & Non-Standard Legal Matters', items: ['Not every legal problem fits neatly into one category.', 'We also assist with complex and unusual matters involving property rights, relatives, police, public authorities, local institutions, documentation and other legal issues arising in Ukraine.'] },
    ],
  },
  notSure: {
    title: 'Not sure what kind of lawyer you need?',
    text: 'You do not need to determine the legal category yourself. Tell us what happened. We will assess the situation and determine what legal action can be taken in Ukraine.',
    cta: 'Describe Your Situation',
  },
  team: {
    title: 'Your Legal Team on the Ground in Ukraine',
    subtitle: 'Ukraine-based lawyers representing clients where Ukrainian law and procedure allow.',
    olga: {
      name: 'Olga Sanamyan',
      role: 'Licensed Advocate in Ukraine · Head of Practice',
      spec: 'Criminal Law • Family Law • Inheritance • Traffic Accidents',
      exp: '20+ years of experience',
      phone: '+38(098)720-83-01',
      phone2: '+38(050)929-53-74',
    },
    kateryna: {
      name: 'Kateryna Yusupova',
      role: 'Licensed Advocate in Ukraine',
      spec: 'Criminal Law • Military Law • Traffic Accidents',
      exp: '25+ years of experience',
      phone: '+38(067)586-07-10',
      email: 'yusupova_lawyer@ukr.net',
    },
  },
  whyUs: {
    title: 'Why Clients Abroad Work With Us',
    items: [
      { icon: '/icons/target.png', title: 'Representation Throughout Ukraine', desc: 'We handle cases across the entire country, not only in Kyiv. Wherever the process allows, we act on your behalf.' },
      { icon: '/icons/communication.png', title: 'Remote-First Communication', desc: 'Telegram, WhatsApp, Viber, email and other convenient channels. We explain Ukrainian legal procedures in clear terms and keep you updated at every stage.' },
      { icon: '/icons/moneybag.png', title: 'Transparent Scope and Fees', desc: 'The initial scope of work and fees are agreed before work begins. Any additional work is discussed separately in advance.' },
    ],
  },
  faq: {
    title: 'Frequently Asked Questions',
    items: [
      { q: 'Do I need to travel to Ukraine?', a: 'In many cases, no. Many legal matters can be handled through a lawyer without your personal presence. If a specific procedure requires your participation, we will tell you in advance.' },
      { q: 'Can you represent me while I am abroad?', a: 'Yes, in many matters. The form of representation depends on the specific procedure. After reviewing your situation, we will explain what type of authorization is required under Ukrainian law.' },
      { q: 'How do I authorize a lawyer in Ukraine?', a: 'It depends on your country and the type of case. After reviewing your situation, we will explain exactly what documents or authorizations are required and how to arrange them from abroad.' },
      { q: 'How can I send documents?', a: 'Scans or photos via Telegram, WhatsApp, Viber or email are enough to start. If originals are needed later, we will tell you how to deliver them safely.' },
      { q: 'Do you handle cases throughout Ukraine?', a: 'Yes. We provide legal representation throughout Ukraine — our work is not limited to Kyiv.' },
      { q: 'Can you assist with unusual or complex legal matters?', a: 'Yes. Not every problem fits a standard category. We handle complex and non-standard matters involving property, relatives, police, authorities and documentation in Ukraine.' },
      { q: 'How will we communicate?', a: 'Through Telegram, WhatsApp, Viber, email or another channel convenient for you. We communicate primarily in writing, which makes coordination across different time zones convenient.' },
      { q: 'How are legal fees determined?', a: 'Fees depend on the nature and complexity of the matter. The scope of work and payment arrangements are discussed individually after an initial review of the situation.' },
      { q: 'How will I receive updates about my case?', a: 'We keep you informed in writing at every significant stage: what has been done, what is in progress and what comes next.' },
      { q: 'What languages can we communicate in?', a: 'Written communication in English is available. You can contact us through Telegram, WhatsApp, Viber or email and send a description of your situation and relevant documents.' },
    ],
  },
  reviews: {
    title: 'Client Reviews',
    items: [
      { name: 'Oleksandr K.', text: "They helped me recover a debt that hadn't been repaid for 2 years. The case was resolved in 3 months. Highly recommend!", service: 'Debt Collection' },
      { name: 'Mariia S.', text: 'A professional approach to a family dispute. Everything was settled amicably, without unnecessary stress or expenses.', service: 'Family Law' },
      { name: 'Progress LLC', text: 'Support for a real estate deal worth UAH 2 million. Everything was verified, the documents are in order. Thank you!', service: 'Real Estate' },
    ],
  },
  contact: {
    title: 'Have a Legal Matter in Ukraine?',
    subtitle: 'Send us a brief description of your situation. You do not need to know which area of law it belongs to.',
    phone: 'Phone',
    email: 'Email',
    address: 'Office Address',
    addressValue: '21 Parkovo-Syretska St. (Tymofiia Shamryla), Kyiv, Ukraine',
    messengers: 'Messengers',
    formTitle: 'Request a Consultation',
    formSubtitle: 'Tell us what happened. Briefly describe your situation and we will explain what information or documents we need next.',
    formName: 'Your name',
    formPhone: 'Phone number',
    formMessage: 'Describe your situation',
    formSubmit: 'Send',
    formSending: 'Sending...',
    formSuccess: 'Thank you! We have received your request and will get back to you.',
    formError: 'Something went wrong. Please try again or contact us via messenger.',
    workingHours: 'Office hours: Mon–Fri, 9:00–18:00 (Kyiv time)',
    alertInvalidPhone: 'Please enter a valid phone number (digits, +, -, () only)',
    alertXss: 'Forbidden characters detected',
    alertCopied: 'Number copied!',
    alertCopyFailed: 'Failed to copy',
    alertRateLimited: 'Too many requests. Please try again later.',
    titlePhoneHint: 'Digits, +, -, () only',
    btnTryAgain: 'Try Again',
  },
  footer: {
    rights: '© 2026 Olga Sanamyan Legal Practice. All rights reserved.',
    privacy: 'Privacy Policy',
  },
};
